default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: RecipeShare_development
  password: LukeLeah1

test:
  <<: *default
  database: RecipeShare_test

production:
  <<: *default
  database: RecipeShare_production
  username: recipe_share
  password: <%= ENV['RECIPE_SHARE_DATABASE_PASSWORD'] %>